declare namespace NodeJS {
  interface ProcessEnv {
    NEXT_PUBLIC_API_BASE_URL: string;
    NEXT_PUBLIC_CDN_BASE_URL: string;
    NEXT_PUBLIC_GOOGLE_ANALYTICS_ID: string;
    NEXT_PUBLIC_KAKAO_APP_KEY: string;
    NEXT_PUBLIC_TURN_SERVER_URL1: string;
    NEXT_PUBLIC_TURN_SERVER_URL2: string;
    NEXT_PUBLIC_TURN_SERVER_URL3: string;
    NEXT_PUBLIC_PORTONE_STORE_ID: string;
    NEXT_PUBLIC_PORTONE_CHANNEL_KEY: string;
  }
}
